# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7854f92c9fd2ba73e0679561e74747d93e7ad4989073040b88fd5f0c124c9a7dc292406a24670c7d5bbaf1f321d1e4a3c919defa14316858dcf3108ab85eca08

test:
  secret_key_base: b8c5906318b84e35336ea15167af52703a9e956be716cec289502ea063cf05ae4f1a410a56f0186803e5beb4768a4f60ee9388aadcb418f984bd5d9baba64077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
